[data]
traits = "broad1.nex"

[calibrations]
Hittite             = [3500, 3600]
Old_Irish           = [1100, 1300]
Classical_Armenian  = [1300, 1600]
Ancient_Greek       = [2400, 2500]
#Luvian              = [3275, 3425]
Vedic_Sanskrit      = [3000, 3500]
Old_English         = [ 950, 1050]
#Old_Persian         = [2375, 2525]
Latin               = [2100, 2200]
#Oscan               = [2100, 2300]
Cornish             = [ 300,  400]
Old_High_German     = [1000, 1100]
Tocharian_B         = [1200, 1500]
Tocharian_A         = [1200, 1500]
#Lycian              = [2350, 2450]
Old_Prussian        = [ 500,  600]
#Umbrian             = [2100, 2300]
Avestan             = [2450, 2550]
Gothic              = [1625, 1675]
Old_West_Norse      = [ 750,  850]
Old_Church_Slavic   = [ 950, 1050]
Sogdian             = [1200, 1400]

[priors]
#tree = ["Coalescent", [4.0]] 
tree = ["Uniform", [4000, 25000]]

[mcmc]
steps = 250000
print = 1000
dump  = 5000
debug = true
