[data]
traits = "broad1.nex"

[calibrations]
Hittite             = [3500, 3600]
Old_Irish           = [1100, 1300]
Classical_Armenian  = [1300, 1600]
Ancient_Greek       = [2400, 2500]
#Luvian              = [3275, 3425]
Vedic_Sanskrit      = [3000, 3500]
Old_English         = [ 950, 1050]
#Old_Persian         = [2375, 2525]
Latin               = [2100, 2200]
#Oscan               = [2100, 2300]
Cornish             = [ 300,  400]
Old_High_German     = [1000, 1100]
Tocharian_B         = [1200, 1500]
Tocharian_A         = [1200, 1500]
#Lycian              = [2350, 2450]
Old_Prussian        = [ 500,  600]
#Umbrian             = [2100, 2300]
Avestan             = [2450, 2550]
Gothic              = [1625, 1675]
Old_West_Norse      = [ 750,  850]
Old_Church_Slavic   = [ 950, 1050]
Sogdian             = [1200, 1400]

[[constraints]]
name = "Inner"
clade = ["Old_Irish", "Irish", "Scots_Gaelic", "Welsh", "Breton", "Cornish", "Latin", "Nuorese", "Cagliari", "Romanian", "Arumanian", "Catalan", "Portuguese", "Spanish", "French", "Provencal", "Walloon", "Ladin", "Romansh", "Friulian", "Italian", "Gothic", "Old_West_Norse", "Icelandic", "Faroese", "Norwegian", "Swedish", "Danish", "Old_English", "English", "Frisian", "Old_High_German", "German", "Luxembourgish", "Swiss_German", "Dutch", "Flemish", "Afrikaans", "Tosk", "Arvanitika", "Ancient_Greek", "Modern_Greek", "Classical_Armenian", "Eastern_Armenian", "Adapazar", "Old_Prussian", "Lithuanian", "Latvian", "Czech", "Slovak", "Polish", "Lower_Sorbian", "Upper_Sorbian", "Ukrainian", "Belarusian", "Russian", "Slovenian", "Macedonian", "Bulgarian", "Serbian", "Old_Church_Slavic", "Avestan", "Pashto", "Waziri", "Tajik", "Persian", "Sogdian", "Wakhi", "Baluchi", "Kurdish", "Zazaki", "Shughni", "Sariqoli", "Digor_Ossetic", "Vedic_Sanskrit", "Nepali", "Assamese", "Oriya", "Bengali", "Bihari", "Marwari", "Hindi", "Urdu", "Sindhi", "Lahnda", "Panjabi", "Gujarati", "Marathi", "Kashmiri", "Singhalese", "Romani"]

[[constraints]]
name = "Nuclear"
clade = ["Inner", "Tocharian_A", "Tocharian_B"]

[[constraints]]
name = "East_Baltic"
clade = ["Latvian", "Lithuanian"]

[[constraints]]
name = "Baltic"
clade = ["Old_Prussian", "East_Baltic"]

[[constraints]]
name = "West_Slavic"
clade = ["Czech", "Slovak", "Polish", "Upper_Sorbian", "Lower_Sorbian"]

[[constraints]]
name = "East_Slavic"
clade = ["Russian", "Belarusian", "Ukrainian"]

[[constraints]]
name = "South_Slavic"
clade = ["Old_Church_Slavic", "Serbian", "Bulgarian", "Macedonian", "Slovenian"]

[[constraints]]
name = "Slavic"
clade = ["West_Slavic", "East_Slavic", "South_Slavic"]

[[constraints]]
name = "Balto_Slavic"
clade = ["Baltic", "Slavic"]

[[constraints]]
name = "West_Norse"
clade = ["Old_West_Norse", "Icelandic", "Faroese", "Norwegian"]

[[constraints]]
name = "East_Norse"
clade = ["Danish", "Swedish"]

[[constraints]]
name = "North_Germanic"
clade = ["West_Norse", "East_Norse"]

[[constraints]]
name = "Anglo"
clade = ["Old_English", "English"]

[[constraints]]
name = "High_German"
clade = ["Old_High_German", "German", "Swiss_German", "Luxembourgish"]

[[constraints]]
name = "West_Germanic"
clade = ["High_German", "Anglo", "Frisian", "Dutch", "Flemish", "Afrikaans"]

[[constraints]]
name = "Germanic"
clade =["Gothic", "West_Germanic", "North_Germanic"]

[[constraints]]
name = "Persian_Tajik"
clade = ["Persian", "Tajik"]

[[constraints]]
name = "Pashto_Waziri"
clade = ["Pashto", "Waziri"]

[[constraints]]
name = "Iranian"
clade = ["Avestan", "Persian_Tajik", "Pashto_Waziri", "Sogdian", "Wakhi", "Baluchi", "Kurdish", "Zazaki", "Shughni", "Sariqoli", "Digor_Ossetic"]

[[constraints]]
name = "Modern_Indo_Aryan"
clade = ["Nepali", "Assamese", "Oriya", "Bengali", "Bihari", "Marwari", "Hindi", "Urdu", "Sindhi", "Lahnda", "Panjabi", "Gujarati", "Marathi", "Kashmiri", "Singhalese", "Romani"]

[[constraints]]
name = "Indo_Aryan"
clade = ["Vedic_Sanskrit", "Modern_Indo_Aryan"]

[[constraints]]
name = "Indo_Iranian"
clade = ["Indo_Aryan", "Iranian"]

[[constraints]]
name = "Eastern_Romance"
clade = ["Romanian", "Arumanian"]

[[constraints]]
name = "Italo_Western_Romance"
clade = ["Catalan", "Portuguese", "Spanish", "French", "Provencal", "Walloon", "Ladin", "Romansh", "Friulian", "Italian"]

[[constraints]]
name = "Continental_Romance"
clade = ["Eastern_Romance", "Italo_Western_Romance"]

[[constraints]]
name = "Sardinian"
clade = ["Nuorese", "Cagliari"]

[[constraints]]
name = "Romance"
clade = ["Sardinian", "Continental_Romance"]

[[constraints]]
name = "Italic"
clade = ["Romance", "Latin"]

[[constraints]]
name = "Albanian"
clade = ["Tosk", "Arvanitika"]

[[constraints]]
name = "Modern_Armenian"
clade = ["Eastern_Armenian", "Adapazar"]

[[constraints]]
name = "Armenian"
clade = ["Modern_Armenian", "Classical_Armenian"]

[[constraints]]
name = "Greek"
clade = ["Ancient_Greek", "Modern_Greek"]

[[constraints]]
name = "Brythonic" 
clade = ["Cornish", "Breton", "Welsh"]

[[constraints]]
name = "Goidelic"
clade = ["Old_Irish", "Irish", "Scots_Gaelic"]

[[constraints]]
name = "Celtic"
clade = ["Brythonic", "Goidelic"]

[[constraints]]
name = "Italo_Celtic"
clade = ["Celtic", "Italic"]


[priors]
tree = ["Coalescent", [5.0]] 
#tree = ["Uniform", [4000, 25000]]

[mcmc]
steps = 5_000_000
print = 10_000
dump  = 10_000
debug = true

