[data]
traits = "narrow1.nex"

[calibrations]
Hittite             = [3500, 3600]
Old_Irish           = [1100, 1300]
Classical_Armenian  = [1300, 1600]
Ancient_Greek       = [2400, 2500]
Vedic_Sanskrit      = [3000, 3500]
Old_English         = [ 950, 1050]
Latin               = [2100, 2200]
Old_High_German     = [1000, 1100]
Tocharian_B         = [1200, 1500]
Avestan             = [2450, 2550]
Gothic              = [1625, 1675]
Old_West_Norse      = [ 750,  850]
Old_Church_Slavic   = [ 950, 1050]

[priors]
tree = ["Uniform", [4000, 25000]]
#tree = ["Coalescent", [4.0]]

[mcmc]
steps = 100000
print = 1000
debug = true
